
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  contextPath:   /auth
  port: 8901

spring:
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    # 若docker使用的DockerToolBox,则localhost为docker-machine的IP地址, 192.168.99.100
    url: jdbc:mysql://${MYSQL_HOST:192.168.3.64}:3306/eagle_eye_dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${MYSQL_DB_USER:root}
    password: ${MYSQL_DB_PASSWD:orvibo888}
    testWhileIdle: true
    validationQuery: SELECT 1